
PORTFOLIO:
  ALLOCATION:
    DEFINED_RISK:
      TARGET_PCT: 80
      MAX_RISK_DOLLARS: 80_000

    UNDEFINED_RISK:
      TARGET_PCT: 20
      MAX_RISK_DOLLARS: 20_000

  DRAWDOWN_LIMITS:
    DAILY_MAX_LOSS_PCT: 2.0             # $2,000
    WEEKLY_MAX_LOSS_PCT: 5.0            # $5,000
    TOTAL_MAX_DRAWDOWN_PCT: 15.0        # $15,000

  ENFORCEMENT:
    ON_DAILY_BREACH: DISABLE_NEW_TRADES
    ON_WEEKLY_BREACH: CLOSE_LOSERS
    ON_TOTAL_BREACH: FLATTEN_ALL


PORTFOLIO_EXPOSURE:
  MAX_SINGLE_UNDERLYING_RISK_PCT: 10.0     # $10,000
  MAX_SECTOR_RISK_PCT: 25.0                # Tech, Financials, etc

  CORRELATION:
    MAX_CORRELATED_POSITIONS: 3
    CORRELATION_LOOKBACK_DAYS: 60
    CORRELATION_THRESHOLD: 0.75

  GREEKS:
    MAX_NET_DELTA_DOLLARS: 20_000
    MAX_NET_GAMMA: 5_000
    MAX_NET_VEGA: 8_000

TRADE_GLOBAL:
  MAX_TRADES_PER_DAY: 5
  MAX_OPEN_TRADES: 20